# Generated by Django 5.1.6 on 2025-03-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_proposal_proposalvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('MEMBER', 'Member')], default='MEMBER', max_length=15),
        ),
    ]
